-- Vintage theme: the editor as a Work surface (IBM 5153 on black).
-- Role names and values come from docs/theme-spec.md; highlights below refer
-- to roles only. The Frame chrome (statusline, tab line, pickers) is #17.
local p = {
  -- Work surface
  work_bg = "#000000",
  work_fg = "#C4C4C4",
  work_cursor = "#4EDC4E",
  work_cursor_text = "#000000",
  work_cursorline = "#161616",
  work_selection = "#000080",
  work_selection_text = "#FFFFFF",
  work_line_number = "#7E7E7E",
  work_grid = "#4E4E4E",
  work_popup_border = "#808080",

  -- ANSI (IBM 5153)
  ansi_0 = "#000000",
  ansi_1 = "#C40000",
  ansi_2 = "#00C400",
  ansi_3 = "#C47E00",
  ansi_4 = "#0000C4",
  ansi_5 = "#C400C4",
  ansi_6 = "#00C4C4",
  ansi_7 = "#C4C4C4",
  ansi_8 = "#4E4E4E",
  ansi_9 = "#DC4E4E",
  ansi_10 = "#4EDC4E",
  ansi_11 = "#F3F34E",
  ansi_12 = "#4E4EDC",
  ansi_13 = "#F34EF3",
  ansi_14 = "#4EF3F3",
  ansi_15 = "#FFFFFF",

  -- Syntax
  syntax_comment = "#7E7E7E",
  syntax_keyword = "#F3F34E",
  syntax_string = "#4EDC4E",
  syntax_number = "#F34EF3",
  syntax_function = "#4EF3F3",
  syntax_type = "#FFFFFF",
  syntax_constant = "#C47E00",
  syntax_operator = "#C4C4C4",
  syntax_error = "#DC4E4E",
  syntax_warning = "#F3F34E",
}

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end
vim.o.background = "dark"
vim.g.colors_name = "vintage"

local groups = {
  -- Editor
  Normal = { fg = p.work_fg, bg = p.work_bg },
  NormalNC = { link = "Normal" },
  Cursor = { fg = p.work_cursor_text, bg = p.work_cursor },
  lCursor = { link = "Cursor" },
  CursorIM = { link = "Cursor" },
  TermCursor = { link = "Cursor" },
  CursorLine = { bg = p.work_cursorline },
  CursorColumn = { link = "CursorLine" },
  ColorColumn = { bg = p.work_grid }, -- the 80-column ruler
  LineNr = { fg = p.work_line_number },
  LineNrAbove = { link = "LineNr" },
  LineNrBelow = { link = "LineNr" },
  CursorLineNr = { fg = p.work_fg, bg = p.work_cursorline },
  SignColumn = { bg = p.work_bg },
  CursorLineSign = { link = "CursorLine" },
  FoldColumn = { fg = p.work_line_number, bg = p.work_bg },
  CursorLineFold = { link = "CursorLine" },
  Folded = { fg = p.work_line_number, bg = p.work_cursorline },
  EndOfBuffer = { fg = p.work_grid },
  NonText = { fg = p.work_grid },
  Whitespace = { fg = p.work_grid },
  SpecialKey = { fg = p.work_grid },
  Conceal = { fg = p.work_line_number },
  WinSeparator = { fg = p.work_grid, bg = p.work_bg },
  VertSplit = { link = "WinSeparator" },
  Visual = { fg = p.work_selection_text, bg = p.work_selection },
  VisualNOS = { link = "Visual" },
  Search = { fg = p.work_selection_text, bg = p.work_selection },
  CurSearch = { fg = p.work_bg, bg = p.syntax_keyword },
  IncSearch = { link = "CurSearch" },
  Substitute = { link = "CurSearch" },
  MatchParen = { fg = p.work_selection_text, bg = p.work_grid },
  Directory = { fg = p.syntax_function },
  Title = { fg = p.syntax_type },
  Question = { fg = p.syntax_string },
  MoreMsg = { fg = p.syntax_string },
  ModeMsg = { fg = p.work_fg },
  MsgArea = { link = "Normal" },
  ErrorMsg = { fg = p.syntax_error },
  WarningMsg = { fg = p.syntax_warning },
  QuickFixLine = { link = "CursorLine" },
  WildMenu = { link = "PmenuSel" },

  -- Placeholder until the Frame statusline and tab line land in #17
  StatusLine = { fg = p.work_bg, bg = p.work_fg },
  StatusLineNC = { fg = p.work_fg, bg = p.work_grid },
  TabLine = { link = "StatusLineNC" },
  TabLineFill = { link = "StatusLineNC" },
  TabLineSel = { link = "StatusLine" },
  WinBar = { link = "Normal" },
  WinBarNC = { link = "Normal" },

  -- Inline code popups: Work surface with a 1px work_popup_border
  NormalFloat = { fg = p.work_fg, bg = p.work_bg },
  FloatBorder = { fg = p.work_popup_border, bg = p.work_bg },
  FloatTitle = { fg = p.work_fg, bg = p.work_bg },
  FloatFooter = { link = "FloatTitle" },
  Pmenu = { fg = p.work_fg, bg = p.work_bg },
  PmenuSel = { fg = p.work_selection_text, bg = p.work_selection },
  PmenuKind = { link = "Pmenu" },
  PmenuKindSel = { link = "PmenuSel" },
  PmenuExtra = { fg = p.work_line_number, bg = p.work_bg },
  PmenuExtraSel = { link = "PmenuSel" },
  PmenuSbar = { bg = p.work_bg },
  PmenuThumb = { bg = p.work_popup_border },
  PmenuMatch = { fg = p.syntax_keyword, bg = p.work_bg },
  PmenuMatchSel = { fg = p.syntax_keyword, bg = p.work_selection },

  -- blink.cmp
  BlinkCmpMenu = { link = "Pmenu" },
  BlinkCmpMenuBorder = { link = "FloatBorder" },
  BlinkCmpMenuSelection = { link = "PmenuSel" },
  BlinkCmpScrollBarThumb = { link = "PmenuThumb" },
  BlinkCmpScrollBarGutter = { link = "PmenuSbar" },
  BlinkCmpLabel = { fg = p.work_fg },
  BlinkCmpLabelDeprecated = { fg = p.work_line_number, strikethrough = true },
  BlinkCmpLabelMatch = { fg = p.syntax_keyword },
  BlinkCmpLabelDetail = { fg = p.work_line_number },
  BlinkCmpLabelDescription = { fg = p.work_line_number },
  BlinkCmpKind = { fg = p.syntax_function },
  BlinkCmpSource = { fg = p.work_line_number },
  BlinkCmpGhostText = { fg = p.work_line_number },
  BlinkCmpDoc = { link = "NormalFloat" },
  BlinkCmpDocBorder = { link = "FloatBorder" },
  BlinkCmpDocSeparator = { link = "FloatBorder" },
  BlinkCmpDocCursorLine = { link = "CursorLine" },
  BlinkCmpSignatureHelp = { link = "NormalFloat" },
  BlinkCmpSignatureHelpBorder = { link = "FloatBorder" },
  BlinkCmpSignatureHelpActiveParameter = { fg = p.work_selection_text, bg = p.work_selection },

  -- Syntax roles
  Comment = { fg = p.syntax_comment },
  Keyword = { fg = p.syntax_keyword },
  Statement = { link = "Keyword" },
  Conditional = { link = "Keyword" },
  Repeat = { link = "Keyword" },
  Label = { link = "Keyword" },
  Exception = { link = "Keyword" },
  PreProc = { link = "Keyword" },
  Include = { link = "Keyword" },
  Define = { link = "Keyword" },
  Macro = { link = "Keyword" },
  PreCondit = { link = "Keyword" },
  StorageClass = { link = "Keyword" },
  String = { fg = p.syntax_string },
  Character = { link = "String" },
  Number = { fg = p.syntax_number },
  Float = { link = "Number" },
  Boolean = { link = "Constant" },
  Constant = { fg = p.syntax_constant },
  Function = { fg = p.syntax_function },
  Identifier = { fg = p.work_fg },
  Type = { fg = p.syntax_type },
  Structure = { link = "Type" },
  Typedef = { link = "Type" },
  Operator = { fg = p.syntax_operator },
  Delimiter = { fg = p.syntax_operator },
  Special = { fg = p.syntax_constant },
  SpecialChar = { link = "Special" },
  Tag = { link = "Function" },
  SpecialComment = { link = "Comment" },
  Debug = { link = "Special" },
  Underlined = { fg = p.syntax_function, underline = true },
  Ignore = { fg = p.work_grid },
  Error = { fg = p.syntax_error },
  Todo = { fg = p.work_bg, bg = p.syntax_keyword },
  Added = { fg = p.ansi_10 },
  Changed = { fg = p.ansi_11 },
  Removed = { fg = p.ansi_9 },
  DiffAdd = { fg = p.ansi_10, bg = p.work_cursorline },
  DiffChange = { fg = p.ansi_11, bg = p.work_cursorline },
  DiffDelete = { fg = p.ansi_9, bg = p.work_cursorline },
  DiffText = { fg = p.work_selection_text, bg = p.work_selection },
  SpellBad = { sp = p.syntax_error, undercurl = true },
  SpellCap = { sp = p.syntax_warning, undercurl = true },
  SpellLocal = { sp = p.syntax_function, undercurl = true },
  SpellRare = { sp = p.syntax_number, undercurl = true },

  -- Diagnostics
  DiagnosticError = { fg = p.syntax_error },
  DiagnosticWarn = { fg = p.syntax_warning },
  DiagnosticInfo = { fg = p.syntax_function },
  DiagnosticHint = { fg = p.work_line_number },
  DiagnosticOk = { fg = p.syntax_string },
  DiagnosticUnderlineError = { sp = p.syntax_error, undercurl = true },
  DiagnosticUnderlineWarn = { sp = p.syntax_warning, undercurl = true },
  DiagnosticUnderlineInfo = { sp = p.syntax_function, undercurl = true },
  DiagnosticUnderlineHint = { sp = p.work_line_number, undercurl = true },
  DiagnosticUnderlineOk = { sp = p.syntax_string, undercurl = true },
  DiagnosticUnnecessary = { fg = p.work_line_number },
  DiagnosticDeprecated = { strikethrough = true },

  -- LSP
  LspReferenceText = { bg = p.work_cursorline },
  LspReferenceRead = { link = "LspReferenceText" },
  LspReferenceWrite = { link = "LspReferenceText" },
  LspSignatureActiveParameter = { link = "BlinkCmpSignatureHelpActiveParameter" },
  LspInlayHint = { fg = p.work_line_number },
  LspCodeLens = { fg = p.work_line_number },

  -- Treesitter
  ["@comment"] = { link = "Comment" },
  ["@comment.error"] = { link = "DiagnosticError" },
  ["@comment.warning"] = { link = "DiagnosticWarn" },
  ["@comment.note"] = { link = "DiagnosticInfo" },
  ["@comment.todo"] = { link = "Todo" },
  ["@keyword"] = { link = "Keyword" },
  ["@keyword.function"] = { link = "Keyword" },
  ["@keyword.return"] = { link = "Keyword" },
  ["@keyword.operator"] = { link = "Keyword" },
  ["@keyword.import"] = { link = "Include" },
  ["@keyword.conditional"] = { link = "Conditional" },
  ["@keyword.repeat"] = { link = "Repeat" },
  ["@keyword.exception"] = { link = "Exception" },
  ["@string"] = { link = "String" },
  ["@string.escape"] = { link = "SpecialChar" },
  ["@string.regexp"] = { link = "SpecialChar" },
  ["@string.special"] = { link = "SpecialChar" },
  ["@string.special.url"] = { link = "Underlined" },
  ["@character"] = { link = "Character" },
  ["@number"] = { link = "Number" },
  ["@number.float"] = { link = "Float" },
  ["@boolean"] = { link = "Boolean" },
  ["@constant"] = { link = "Constant" },
  ["@constant.builtin"] = { link = "Constant" },
  ["@function"] = { link = "Function" },
  ["@function.builtin"] = { link = "Function" },
  ["@function.call"] = { link = "Function" },
  ["@function.method"] = { link = "Function" },
  ["@function.method.call"] = { link = "Function" },
  ["@constructor"] = { link = "Type" },
  ["@type"] = { link = "Type" },
  ["@type.builtin"] = { link = "Type" },
  ["@type.definition"] = { link = "Type" },
  ["@module"] = { link = "Type" },
  ["@variable"] = { fg = p.work_fg },
  ["@variable.builtin"] = { link = "Constant" },
  ["@variable.parameter"] = { fg = p.work_fg },
  ["@variable.member"] = { fg = p.work_fg },
  ["@property"] = { fg = p.work_fg },
  ["@attribute"] = { link = "PreProc" },
  ["@label"] = { link = "Label" },
  ["@operator"] = { link = "Operator" },
  ["@punctuation"] = { link = "Delimiter" },
  ["@punctuation.special"] = { link = "Special" },
  ["@tag"] = { link = "Tag" },
  ["@tag.attribute"] = { fg = p.work_fg },
  ["@tag.delimiter"] = { link = "Delimiter" },
  ["@markup.heading"] = { link = "Title" },
  ["@markup.strong"] = { fg = p.syntax_type }, -- emphasis comes from color only
  ["@markup.italic"] = { fg = p.syntax_type },
  ["@markup.strikethrough"] = { strikethrough = true },
  ["@markup.underline"] = { underline = true },
  ["@markup.link"] = { link = "Function" },
  ["@markup.link.url"] = { link = "Underlined" },
  ["@markup.raw"] = { link = "String" },
  ["@markup.list"] = { link = "Special" },
  ["@markup.quote"] = { link = "Comment" },
  ["@diff.plus"] = { link = "Added" },
  ["@diff.minus"] = { link = "Removed" },
  ["@diff.delta"] = { link = "Changed" },

  -- LSP semantic tokens
  ["@lsp.type.class"] = { link = "@type" },
  ["@lsp.type.enum"] = { link = "@type" },
  ["@lsp.type.interface"] = { link = "@type" },
  ["@lsp.type.struct"] = { link = "@type" },
  ["@lsp.type.type"] = { link = "@type" },
  ["@lsp.type.typeParameter"] = { link = "@type" },
  ["@lsp.type.namespace"] = { link = "@module" },
  ["@lsp.type.function"] = { link = "@function" },
  ["@lsp.type.method"] = { link = "@function.method" },
  ["@lsp.type.macro"] = { link = "Macro" },
  ["@lsp.type.keyword"] = { link = "@keyword" },
  ["@lsp.type.string"] = { link = "@string" },
  ["@lsp.type.number"] = { link = "@number" },
  ["@lsp.type.comment"] = { link = "@comment" },
  ["@lsp.type.enumMember"] = { link = "@constant" },
  ["@lsp.type.parameter"] = { link = "@variable.parameter" },
  ["@lsp.type.property"] = { link = "@property" },
  ["@lsp.type.variable"] = { link = "@variable" },
  ["@lsp.type.operator"] = { link = "@operator" },
  ["@lsp.mod.deprecated"] = { link = "DiagnosticDeprecated" },
}

for group, attrs in pairs(groups) do
  vim.api.nvim_set_hl(0, group, attrs)
end

-- :terminal follows the same 16 colors as Ghostty
for i = 0, 15 do
  vim.g["terminal_color_" .. i] = p["ansi_" .. i]
end
