# Pixel icons for the bar: 16x16 grids written as 2x PNGs for Retina.
# Pure stdlib, no PIL. Edit a grid, then: python3 make_icons.py
import os, struct, zlib

PAL = {
    ".": None,
    "k": (0, 0, 0), "w": (255, 255, 255), "g": (192, 192, 192), "d": (128, 128, 128),
    "y": (255, 255, 0), "o": (128, 128, 0), "r": (255, 0, 0), "R": (128, 0, 0),
    "G": (0, 128, 0), "L": (0, 255, 0), "b": (0, 0, 128), "B": (0, 0, 255), "c": (0, 255, 255),
}

def png(path, rows, scale=2):
    h, w = len(rows), len(rows[0])
    raw = b""
    for row in rows:
        line = b""
        for ch in row:
            c = PAL[ch]
            px = b"\0\0\0\0" if c is None else bytes(c) + b"\xff"
            line += px * scale
        raw += (b"\0" + line) * scale
    def chunk(t, d):
        return struct.pack(">I", len(d)) + t + d + struct.pack(">I", zlib.crc32(t + d) & 0xffffffff)
    data = b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", w * scale, h * scale, 8, 6, 0, 0, 0))
    data += chunk(b"IDAT", zlib.compress(raw)) + chunk(b"IEND", b"")
    with open(path, "wb") as f:
        f.write(data)

def grid(s):
    rows = [r for r in s.strip("\n").split("\n")]
    assert all(len(r) == 16 for r in rows) and len(rows) == 16, s
    return rows

ICONS = {}

ICONS["start"] = grid("""
................
................
..rrrrr.........
..rrrrr.GGGGG...
..rrrrr.GGGGG...
..rrrrr.GGGGG...
..rrrrr.GGGGG...
........GGGGG...
..BBBBB.........
..BBBBB.yyyyy...
..BBBBB.yyyyy...
..BBBBB.yyyyy...
..BBBBB.yyyyy...
........yyyyy...
................
................
""")

SPEAKER = """
................
................
.......k........
......kk........
.....kwk........
.kkkkwgk........
.kwwwggk........
.kwgggdk........
.kwgggdk........
.kdddddk........
.kkkkkdk........
.....kdk........
......kk........
.......k........
................
................
"""
def overlay(base, marks):
    rows = [list(r) for r in grid(base)]
    for (x, y), ch in marks.items():
        rows[y][x] = ch
    return ["".join(r) for r in rows]

waves = {(10, 6): "k", (10, 7): "k", (10, 8): "k", (10, 9): "k",
         (12, 4): "k", (13, 5): "k", (13, 6): "k", (13, 7): "k", (13, 8): "k", (13, 9): "k", (13, 10): "k", (12, 11): "k"}
ICONS["volume"] = overlay(SPEAKER, waves)
ICONS["volume_low"] = overlay(SPEAKER, {k: v for k, v in waves.items() if k[0] == 10})
ICONS["volume_mute"] = overlay(SPEAKER, {(10, 5): "r", (11, 6): "r", (12, 7): "r", (13, 8): "r", (14, 9): "r",
                                         (14, 5): "r", (13, 6): "r", (11, 8): "r", (10, 9): "r"})

def battery(level, fill, bolt=False):
    rows = [["."] * 16 for _ in range(16)]
    for x in range(1, 14):
        rows[4][x] = rows[11][x] = "k"
    for y in range(4, 12):
        rows[y][1] = rows[y][13] = "k"
    for y in range(6, 10):
        rows[y][14] = "k"
    for y in range(5, 11):
        for x in range(2, 13):
            rows[y][x] = "w"
    for y in range(6, 10):
        for x in range(3, 3 + level):
            rows[y][x] = fill
    if bolt:
        for x, y in [(7, 6), (6, 7), (7, 7), (8, 7), (9, 7), (7, 8), (8, 8), (7, 9)]:
            rows[y][x] = "y"
    return ["".join(r) for r in rows]

ICONS["battery_100"] = battery(9, "G")
ICONS["battery_75"] = battery(7, "G")
ICONS["battery_50"] = battery(5, "o")
ICONS["battery_25"] = battery(3, "R")
ICONS["battery_low"] = battery(1, "r")
ICONS["battery_charging"] = battery(9, "G", bolt=True)

def bars(color, off=False):
    rows = [["."] * 16 for _ in range(16)]
    for i, h in enumerate([3, 6, 9, 12]):
        x0 = 1 + i * 4
        for y in range(14 - h, 14):
            for x in range(x0, x0 + 3):
                rows[y][x] = "k" if x in (x0, x0 + 2) or y == 14 - h or y == 13 else color
    if off:
        for i in range(10):
            rows[3 + i][3 + i] = "r"
            rows[3 + i][12 - i] = "r"
    return ["".join(r) for r in rows]

ICONS["wifi"] = bars("L")
ICONS["wifi_off"] = bars("d", off=True)

ICONS["sun"] = grid("""
................
.......y........
..y....y....y...
...y.......y....
......yyy.......
....yyyyyyy.....
....yyyyyyy.....
.yy.yyyyyyy.yy..
....yyyyyyy.....
....yyyyyyy.....
......yyy.......
...y.......y....
..y....y....y...
.......y........
................
................
""")

CLOUD = """
................
................
................
................
......kkkk......
.....kwwwwk.....
..kkkwwwwwwkk...
.kwwwwwwwwwwwk..
kwwwwwwwwwwwwwk.
kwwwwwwwwwwwggk.
kgwwwwwwwwwgggk.
.kkkkkkkkkkkkk..
................
................
................
................
"""
ICONS["cloud"] = grid(CLOUD)
ICONS["partly_cloudy"] = overlay(CLOUD, {(x, y): "y" for x in range(8, 16) for y in range(0, 7)
                                         if (x - 12) ** 2 + (y - 3) ** 2 <= 8 and grid(CLOUD)[y][x] == "."})
ICONS["rain"] = overlay(CLOUD, {(3, 13): "B", (2, 14): "B", (7, 13): "B", (6, 14): "B", (11, 13): "B", (10, 14): "B"})
ICONS["storm"] = overlay(CLOUD, {(7, 12): "y", (6, 13): "y", (7, 13): "y", (8, 13): "y", (7, 14): "y", (6, 15): "y",
                                 (3, 13): "B", (11, 13): "B"})
ICONS["snow"] = overlay(CLOUD, {(3, 13): "c", (7, 14): "c", (11, 13): "c", (5, 15): "c", (9, 15): "c"})
ICONS["lock"] = grid("""
................
................
................
......kkkk......
.....k....k.....
.....k....k.....
.....k....k.....
....kkkkkkkk....
....kyyyyyyk....
....kyyokyyk....
....kyyokyyk....
....kyyyyyyk....
....kkkkkkkk....
................
................
................
""")
ICONS["fog"] = overlay(CLOUD, {(x, y): "d" for y in (13, 15) for x in range(1, 15) if (x + y) % 3})

here = os.path.dirname(os.path.abspath(__file__))
for name, rows in ICONS.items():
    png(os.path.join(here, name + ".png"), rows)
print("wrote", len(ICONS), "icons")
